-- 002_user_profile.sql

ALTER TABLE users ADD COLUMN IF NOT EXISTS display_name TEXT;
ALTER TABLE users ADD COLUMN IF NOT EXISTS avatar_data  BYTEA;
ALTER TABLE users ADD COLUMN IF NOT EXISTS avatar_mime  TEXT;
ALTER TABLE users ADD COLUMN IF NOT EXISTS updated_at   TIMESTAMPTZ NOT NULL DEFAULT now();
